name: flutter_clean_coded
description: Flutter Clean Architecture Series to build a Flutter App with Clean Code!
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  ionicons: ^0.2.2

  # UI
  introduction_screen: ^3.1.17
  lottie: ^3.3.1


  # DI
  get_it: ^8.0.3

  # Networking
  dio: ^5.8.0+1
  internet_connection_checker_plus: ^2.7.2

  # State Management
  flutter_bloc: ^9.1.1

  # UI Libraries
  loading_animation_widget: ^1.3.0
  toastification: ^3.0.3
  animate_do: ^4.2.0
  pretty_dio_logger: ^1.4.0
  fl_chart: ^1.0.0


  # Notification
  awesome_notifications_core: ^0.10.1
  awesome_notifications: ^0.10.1


  # Flutter Core
  dart_secure: ^0.6.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  share_plus: ^11.0.0
  pdf: ^3.11.3
  qr_flutter: ^4.1.0
  syncfusion_flutter_datepicker: ^30.1.41
  flutter_inappwebview: ^6.1.15
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.2.0


  # App Logging
  #  firebase_crashlytics: ^4.2.0
  #  firebase_analytics: ^11.3.6
  #  firebase_performance: ^0.10.0+11

  # cache
  cached_network_image: ^3.4.1


#dependency_overrides:
#  intl: ^0.20.1

#dart run flutter_launcher_icons
flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_logo.png"




dev_dependencies:
  # Dev Core Packages
  device_preview: ^1.3.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"

  # Other
  flutter_lints: ^6.0.0
  lint: ^2.8.0



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/font/
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/images/company/
    - assets/animations/intro_screen/
    - shorebird.yaml
    - .env

    

  fonts:
    - family: poppins
      fonts:
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700

        - asset: assets/font/Poppins-Medium.ttf
          style: normal
          weight: 400

        - asset: assets/font/Poppins-Italic.ttf
          style: italic
          weight: 400